" Zero dependencies vimrc

let s:is_win = has('win32') || has('win64')

syntax enable
set nocompatible
set termguicolors
colorscheme naz

set hidden            " :q will act like :hide
set confirm           " Ask to save changes or not if closing last window
set nobackup          " Don't keep a backup file after overwriting a file
set nowritebackup     " Don't make a backup before overwriting a file

set number            " Show line numbers
set norelativenumber  " !Show relative line numbers
set scrolloff=5       " Keep lines of context around the cursor
set backspace=indent,eol,start

set showcmd
set showcmdloc=last   " Show commands on the last line

set wildoptions=pum   " Show wildmenu as a pop-up
set formatoptions-=c fo-=r fo-=o fo-=t " Disable comment leader insertion and automatic line breaks


"============================================================
" Searching
"============================================================
set incsearch         " Incremental search
set hlsearch          " Highlight search results
set ignorecase        " Ignore case when searching
set smartcase         " Respect case if the query contains uppercase letters
set showmatch         " Highlight matching parenthesis.
set tags+=tags;
command! Ctags silent execute '!ctags -R --c-kinds=+p .' | redraw!


"============================================================
" Indentation
"============================================================
set expandtab         " Use spaces instead of tabs
set tabstop=2         " Number of spaces a <Tab> counts for
set shiftwidth=2      " Number of spaces to use for auto-indentation
set softtabstop=2     " Number of spaces <Tab> inserts in edit mode
set autoindent        " Copy indent from current line when starting a new one
set cindent           " Use C-style indentation
set smartindent

" Make trailing whitespace chars visible
set list
set listchars=tab:▸\ ,trail:·


"============================================================
" Terminal
"============================================================
tnoremap <Esc> <C-\><C-n>

"------------------------------
" Global terminal buffer
"
let s:germinal_name = "(GERMINAL)"
let s:germinal_bufnr = bufnr(s:germinal_name)

" The mode arg is used to change the way to invoke the germinal (should only be one instance/buffer).
" A function call will have different behaviors based on the fact that: -> `X. (applies to modes) ...`
"     A. (modes [0-3]) The germinal buf is `UNLISTED` (does not exist, buffer not created)
"     B. (modes [0-3]) The germinal buf is `IN_VIEW`  (open on any window in the active tab);
"     C. (mode 3)      The germinal buf is `IN_A_TAB` (open on any tab).
"
" `a:modes`:
"     0:
"       A.`UNLISTED`-> create and open a germinal buf on the active window;
"       B.`IN_VIEW` -> jump the cursor to the germinal buf.
"     1:
"       A.`UNLISTED`-> do a horizontal split on the active window, and create and open a germinal buf;
"       B.`IN_VIEW` -> hide/close the germinal buf window, do a horizontal split on the active window,
"                      and open a germinal buf;
"     2:
"       A.`UNLISTED`-> same as mode 1, but doing a vertical split
"       B.`IN_VIEW` -> same as mode 1, but doing a vertical split
"     3:
"       A.`UNLISTED`-> create a new tab, and create and open a germinal buf;
"       B.`IN_VIEW` -> hide/close the germinal buf window, and (C)... ;
"       C.`IN_A_TAB`-> activate the first tab that has a germinal buf open, else create a new tab, and
"                      open the germinal buf.
function! GlobalTerminal(mode)
  let s:germinal_bufnr = bufnr(s:germinal_name)

  if s:germinal_bufnr == -1
    echom '[GlobalTerminal] New terminal buffer assigned to ' . s:germinal_name

    if a:mode == 1
      execute 'horizontal split'
    elseif a:mode == 2
      execute 'vertical split'
    elseif a:mode == 3
      execute 'tabnew'
    endif

    execute has('nvim') ? 'terminal' : 'terminal ++curwin'
    execute 'file ' . s:germinal_name
    sleep 500m
  else
    echom '[GlobalTerminal] Using ' . s:germinal_name

    " Check if the buf is visible and will split
    let l:winnr = bufwinnr(s:germinal_bufnr)
    if l:winnr != -1
      " Is in view
      if a:mode == 0
        execute l:winnr . 'wincmd w'
        return
      else
        execute l:winnr . 'hide'
      endif
    endif

    if a:mode == 3
      " Loop through the tabs checking if there's one germinal buf open
      let l:first_tabpagenr_with_germinal = -1
      for i in range(tabpagenr('$'))
        if index(tabpagebuflist(i + 1), s:germinal_bufnr) != -1
          let l:first_tabpagenr_with_germinal = i + 1
          break
        endif
      endfor

      if l:first_tabpagenr_with_germinal > 0
        execute 'tabnext ' . l:first_tabpagenr_with_germinal
        execute bufwinnr(s:germinal_bufnr) . 'wincmd w'
        return
      else
        execute '$tabnew'
      endif
    else
      if a:mode == 1
        execute 'horizontal split'
      elseif a:mode == 2
        execute 'vertical split'
      endif
    endif

    execute 'buf ' . s:germinal_bufnr
  endif
endfunction

command! Germ call GlobalTerminal(0)
command! Serm call GlobalTerminal(1)
command! Verm call GlobalTerminal(2)
command! Term call GlobalTerminal(3)
command! Germinal call GlobalTerminal(0)
command! Serminal call GlobalTerminal(1)
command! Verminal call GlobalTerminal(2)
command! Terminal call GlobalTerminal(3)

function! GerminalHere(mode)
  let l:head_dir = (&filetype == 'netrw') ? b:netrw_curdir : expand('%:p:h')
  call GlobalTerminal(a:mode)
  call feedkeys("i\<C-c> cd " . ShellEscape(l:head_dir) . "\<CR>\<Esc>", 't')
endfunction

command! Germhere call GerminalHere(0)
command! Sermhere call GerminalHere(1)
command! Vermhere call GerminalHere(2)
command! Termhere call GerminalHere(3)
command! Herm call GerminalHere(3)


"============================================================
" Compiling & Debugging
"============================================================
"------------------------------
" Compiler
"
if s:is_win
  let s:c_compiler = "clang"
  let s:cpp_compiler = "clang++"
else
  let s:c_compiler = "gcc"
  let s:cpp_compiler = "g++"
endif

" Base and warning flags
let s:common_flags = "-Wall -Wextra -Wpedantic"
let s:c_flags = s:common_flags . " -std=c99"
let s:cpp_flags = s:common_flags . " -std=c++03"

" Output program path
let s:out_path = "%:p:h" . "/build/" . "%:t:r" . (s:is_win ? ".exe" : "")


"------------------------------
" Commands (makeprg)
"
if !exists('s:makeprg_cmd_name')
  let s:makeprg_cmd_name = '____'
endif

command! Makeclear let &makeprg='' | let s:makeprg_cmd_name = '____' | redrawtabline

function! s:SetMakeprg(name, cmd)
  let s:makeprg_cmd_name = a:name
  let &makeprg = a:cmd
  redrawtabline
  echo '==> ' . a:name . ' [' . a:cmd . '] set as &makeprg <=='
endfunction

" C debug build (default for .c)
command! Make call s:SetMakeprg('Make', printf('%s -g -O0 %s "%%:p" -o "%s"', s:c_compiler, s:c_flags, s:out_path))

" C final build
command! MakeRelease call s:SetMakeprg('MakeRelease', printf('%s -O3 %s "%%:p" -o "%s"', s:c_compiler, s:c_flags, s:out_path))

" C++ debug build (default for .cpp)
command! Makecpp call s:SetMakeprg('Makecpp', printf('%s -g -O0 %s "%%:p" -o "%s"', s:cpp_compiler, s:cpp_flags, s:out_path))

" C++ final build
command! MakecppRelease call s:SetMakeprg('MakecppRelease', printf('%s -O3 %s "%%:p" -o "%s"', s:cpp_compiler, s:cpp_flags, s:out_path))

" C fsyntax-only
command! Makefsyntax call s:SetMakeprg('Makefsyntax', printf('%s -fsyntax-only %s "%%:p"', s:c_compiler, s:c_flags))

" C++ fsyntax-only
command! Makecppfsyntax call s:SetMakeprg('Makecppfsyntax', printf('%s -fsyntax-only %s "%%:p"', s:cpp_compiler, s:cpp_flags))

" MSVC debug build (need vcvars env)
command! Makecl call s:SetMakeprg('Makecl', 'cd build && cl /Zi /Od /W4 "%:p"')

" MSVC final build (need vcvars env)
command! MakeclRelease call s:SetMakeprg('MakeclRelease', 'cd build && cl /O2 /W4 "%:p"')

" Copy makeprg to clipboard
command! Cpmakeprg :let @+ = &makeprg | echo '==> ' . s:makeprg_cmd_name . ' [' . @+ . '] copied to the clipboard <=='

" Copy expanded makeprg to clipboard
command! Cpmake :let @+ = expandcmd(&makeprg) | echo '==> ' . s:makeprg_cmd_name . ' (expanded) [' . @+ . '] copied to the clipboard <=='

"------------------------------
" Quickfix List
"
" Prepend regex to parse (%f, %l, %t, %m) compiler/linker output correctly for QFListCount()
if !exists('s:prepend_regex_errorformat')
  let s:prepend_regex_errorformat = 1
  set errorformat& " Reset errorformat to default

  " Clang/GCC
  set errorformat^=%f:%l:%c:\ %t%*[^:]:\ %m

  " MSVC Compiler (`file.cpp(#line): error C2065: ...`)
  set errorformat^=%f(%l):\ %t%*[^:]:\ %m

  " MSVC Linker (`file.obj : error LNK2019: ...`)
  set errorformat^=%f\ :\ %t%*[^:]:\ %m

  " MSVC Linker Fatal (`file.obj : fatal error LNK2019: ...`)
  set errorformat^=%f\ :\ fatal\ %t%*[^:]:\ %m
endif

if !exists('s:qf_entries')
  let s:qf_entries = 0
  let s:qf_errors = 0
  let s:qf_warnings = 0
endif

function! s:QFListCount()
  let l:qf_list = getqflist()

  let l:entries = 0
  let l:errors = 0
  let l:warnings = 0

  for l:item in l:qf_list
    if l:item.valid
      let l:entries += 1
      if l:item.type ==? 'E'
        let l:errors += 1
      elseif l:item.type ==? 'W'
        let l:warnings += 1
      endif
    endif
  endfor

  let s:qf_entries = l:entries
  let s:qf_errors = l:errors
  let s:qf_warnings = l:warnings

  if s:qf_entries > 0
    echom printf("[s:QFListCount] Entries: %d | Errors: %d | Warnings: %d", s:qf_entries, s:qf_errors, s:qf_warnings)
  else
    echom '[s:QFListCount] Quickfix list is empty'
  endif
endfunction

function! QFTabline()
  return (s:qf_entries > 0) ? printf("E:%d|W:%d", s:qf_errors, s:qf_warnings) : 'E:_|W:_'
endfunction

augroup QFUpdate
  autocmd!
  autocmd QuickFixCmdPost [^l]* call s:QFListCount()
augroup END

command! Ccount call s:QFListCount()

"------------------------------
" Build
"
" `:redraw!` seems to be needed on my current linux terminal emulator
function! s:BuildAndDebug()
  " Create build directory
  let l:build_dir = expand("%:p:h") . "/build"
  if !isdirectory(l:build_dir)
    call mkdir(l:build_dir, "p")
  endif

  let l:prg_path = l:build_dir . "/" . expand("%:t:r")

  execute 'w'
  execute 'silent make!'

  if s:qf_errors < 1
    if s:is_win
      " Lauch RAD Debugger on Windows
      call system(printf("start raddbg.exe \"%s.exe\"", l:prg_path))
      echo '==> Build Successful (s:qf_entries:' . s:qf_entries . ') - RAD Debugger Launched <=='
      if s:qf_entries < 1
        execute 'cclose'
      endif
    else
      " Launch GDB in a new terminal
      let l:gdb_args = '-tui -ex "layout split" -ex "set print pretty" -ex "set logging file gdb_out.log" -ex "set logging enable on"'
      call system(printf("xfce4-terminal --execute gdb %s \"%s\" &", l:gdb_args, l:prg_path))
      echo '==> Build Successful (s:qf_entries:' . s:qf_entries . ') - GDB Launched <=='
      execute 'redraw!'
    endif
  else
    echohl ErrorMsg | echo '==> Build Failed <==' | echohl None
    execute 'cw'
  endif
endfunction

function! s:BuildAndCheck()
 " Create build directory
  let l:build_dir = expand("%:p:h") . "/build"
  if !isdirectory(l:build_dir)
    call mkdir(l:build_dir, "p")
  endif

  execute 'w'
  execute 'silent make!'

  if !s:is_win
    execute 'redraw!'
  endif

  if s:qf_errors > 0
    let @/ = "error"
    execute 'copen'
    echohl ErrorMsg | echo '==> Build Failed <==' | echohl None
  elseif s:qf_warnings > 0
    echohl WarningMsg | echo '==> Build finished with ' . s:qf_entries . ' issue(s) <==' | echohl None
  else
    echohl OkMsg | echo '==> Build Successful <==' | echohl None
    execute 'cclose'
  endif
endfunction

command! Raddbg call s:BuildAndDebug()
command! Build call s:BuildAndCheck()
nnoremap <F10> :Raddbg<CR>
nnoremap <F5> :Build<CR>


"============================================================
" Misc & Netrw
"============================================================
function! ShellEscape(str)
  if s:is_win
    return '"' . tr(a:str, '/', '\') . '"'
  else
    return shellescape(a:str)
  endif
endfunction

let g:netrw_keepdir = 0

"------------------------------
" Marked files list
"
if !exists('s:nazrw_mark_list')
  let s:nazrw_mark_list = []
endif

function! s:NazrwUpdateMarkList()
  let s:nazrw_mark_list = netrw#Expose("netrwmarkfilelist")
  if type(s:nazrw_mark_list) == type("") || empty(s:nazrw_mark_list)
    let s:nazrw_mark_list = []
  endif
  redrawstatus
endfunction

function! s:NazrwShowMarkList(last)
  call s:NazrwUpdateMarkList()
  if empty(s:nazrw_mark_list)
    echohl Directory | echo '==> Mark list is empty <==' | echohl None
    return
  else
    " copy the mark list with relative paths
    let l:rel_mark_list = map(copy(s:nazrw_mark_list), "fnamemodify(v:val, ':.')")
    let l:len_mark_list = len(l:rel_mark_list)

    if a:last
      echohl Directory | echo '* ' . l:rel_mark_list[l:len_mark_list - 1] . ' ('. (l:len_mark_list - 1) . ' more...)' | echohl None
    else
      echohl Directory | echo '[' . len(l:rel_mark_list) . '] marks:' | echohl None
      echo '* ' . join(l:rel_mark_list, "\n* ")
    endif
  endif
endfunction

"------------------------------
" Copy / Move
"
function! s:GetCopyMoveCmd(is_move, is_dir)
  if a:is_move
    if s:is_win
      return 'move /Y'
    else
      return 'mv -f'
    endif
  else
    if s:is_win
      return (a:is_dir) ? 'xcopy /E /I /Q /H /Y' : 'copy /Y'
    else
      return 'cp -rf'
    endif
  endif
endfunction

function! s:NazrwCopyMove(is_move)
  call s:NazrwUpdateMarkList()
  if empty(s:nazrw_mark_list)
    echohl Directory | echo '==> Mark list is empty <==' | echohl None
    return
  endif

  " Choices: [1]'Yes', [2]'No', [3]'All' (:help confirm() -> [0] is for <Esc>, CTRL-C)
  let l:choice = 2

  for l:curr_file in s:nazrw_mark_list
    " Use regex to remove trailing slashes ('/' or '\'), so `:t` also return directories (for '~/dir//', tail is 'dir')
    let l:src_path = fnamemodify(l:curr_file, ':p')
    let l:src_path = substitute(l:src_path, '[/\\]\+$', '', '')
    let l:dest_path = b:netrw_curdir . '/' . fnamemodify(l:src_path, ':t')

    let l:cmd = s:GetCopyMoveCmd(a:is_move, isdirectory(l:src_path))

"[DEBUG]echom 'l:cmd: '. l:cmd
"[DEBUG]echom 'l:src_path: '. l:src_path
"[DEBUG]echom 'l:dest_path: ' . l:dest_path

    " Check for overwrite and escape ([0] <Esc>)
    if (filereadable(l:dest_path) || isdirectory(l:dest_path)) && l:choice != 3
      let l:choice = confirm("Confirm overwrite of file [" . l:dest_path . ']?', "&yes\n&no\n&all")
      if l:choice == 0
        echom '[s:NazrwCopyMove()] Aborted.'
        break
      elseif l:choice == 2
        continue
      endif
    endif

    let l:src_path = ShellEscape(l:src_path)
    let l:dest_path = ShellEscape(l:dest_path)

    echom '[s:NazrwCopyMove()]$ ' . l:cmd . ' ' . l:src_path . ' ' . l:dest_path
    call system(l:cmd . ' ' . l:src_path . ' ' . l:dest_path)
  endfor

  call netrw#Modify("netrwmarkfilelist", [])
  let s:nazrw_mark_list = []

  execute "normal \<C-l>"
endfunction

"------------------------------
" Archiving
"
let s:default_archive_ext = 'zip'

"NOTE: Implement archive path directory creation, if doesn't exist
function! s:NazrwArchive()
  call s:NazrwUpdateMarkList()
  if empty(s:nazrw_mark_list)
    echohl Directory | echo '==> Mark list is empty <==' | echohl None
    return
  endif

  let l:cmd = 'tar -acf '

  " Prompt for the archive file path. If no extention is given, a default one is assigned (input() doesn't add a '\n')
  let l:archive_path = input('Archive path: ', b:netrw_curdir . '/nazrw_archive.' . s:default_archive_ext, 'file')
  echo "\n"

  if empty(l:archive_path)
    " input() return an empty string for <Esc>
    echom '[s:NazrwArchive()] Aborted.'
    return
  elseif empty(fnamemodify(l:archive_path, ':e'))
    " No archive extension provided, set default archiving method
    let l:archive_path .= '.' . s:default_archive_ext
  endif

  let l:cmd .= ShellEscape(l:archive_path)

  " Loop through the files in the mark list and append ` -C file_head file_tail` to the tar command
  for l:curr_file in s:nazrw_mark_list
    " Use regex to remove trailing slashes ('/' or '\'), so `:t` also return directories (for '~/dir//', tail is 'dir')
    let l:curr_file = substitute(l:curr_file, '[/\\]\+$', '', '')
    let l:cmd .= ' -C ' . ShellEscape(fnamemodify(l:curr_file, ':h')) . ' ' . ShellEscape(fnamemodify(l:curr_file, ':t'))
  endfor

  echom '[s:NazrwArchive()]$ ' . l:cmd
  call system(l:cmd)

  call netrw#Modify("netrwmarkfilelist", [])
  let s:nazrw_mark_list = []

  execute "normal \<C-l>"
endfunction

function! s:NazrwExtract()
  " Loop through marked files (do some checking ...) and prompt for the directory where
  " the contents of the archives should be extracted. Behave like 7Zip `Extract To`
  return
endfunction

"------------------------------
" Commands
"
command! Nazrwcp    call s:NazrwCopyMove(0)
command! Nazrwmv    call s:NazrwCopyMove(1)
command! Nazrwzip   call s:NazrwArchive()
command! Nazrwunzip call s:NazrwExtract()
command! Marklist   call s:NazrwShowMarkList(0)
command! Marklast   call s:NazrwShowMarkList(1)

augroup NazNetrw
  autocmd!
  " [Y]-> Copy file/dir path under the cursor on Netrw
  autocmd Filetype netrw nnoremap <buffer> Y  :let @+ = ShellEscape(b:netrw_curdir . '/' . expand('<cfile>')) <bar> echo '==> [' . @+ . '] copied to the clipboard <=='<CR>
  autocmd Filetype netrw nnoremap <buffer> ~  :e ~/<CR>
  autocmd Filetype netrw nnoremap <buffer> mp :Nazrwcp<CR>
  autocmd Filetype netrw nnoremap <buffer> mv :Nazrwmv<CR>
  autocmd Filetype netrw nnoremap <buffer> mz :Nazrwzip<CR>
  autocmd Filetype netrw nnoremap <buffer> mZ :Nazrwunzip<CR>
  autocmd Filetype netrw nnoremap <buffer> mu :call netrw#Modify("netrwmarkfilelist", []) <bar> Marklast<CR>
  autocmd Filetype netrw nnoremap <buffer> ml :Marklist<CR>
  autocmd Filetype netrw nnoremap <buffer> mL :Marklast<CR>
  autocmd Filetype netrw nmap     <buffer> ;  mf:Marklast<CR>j
  autocmd Filetype netrw nmap     <buffer> ,  mf:Marklast<CR>k
augroup END

command! Cpath :let @+ = ShellEscape((&filetype == 'netrw') ? b:netrw_curdir : expand('%:p')) | echo '==> [' . @+ . '] copied to the clipboard <=='

let mapleader = "\<Backspace>"
nnoremap <leader>cop :copen<CR>
nnoremap <leader>ccl :cclose<CR>
nnoremap <leader>src :source $MYVIMRC <bar> redraw! <bar> redrawtabline <bar> redrawstatus <CR> :echo "==> sourced vimrc <=="<CR>
nnoremap <leader>erc :tab drop $MYVIMRC <bar> silent /makeprg<CR> zz


"============================================================
" Tabline & Statusline
"============================================================
set showtabline=2     " Always show tabline
set laststatus=2      " Always show statusline

let s:superscripts = ['⁰', '¹', '²', '³', '⁴', '⁵', '⁶', '⁷', '⁸', '⁹']

nnoremap <C-S-PageDown> :tabmove +1<CR>
nnoremap <C-S-PageUp> :tabmove -1<CR>

"------------------------------
" Tabline
"
" :help setting-tabline
function! NazTabline()
  let l:tabline_str = ''

  " Loop through each tab page
  for l:i in range(tabpagenr('$'))
    " Set the highlighting
    if l:i + 1 == tabpagenr()
      let l:tabline_str .= '%#TabLineSel#'
    else
      let l:tabline_str .= '%#TabLine#'
    endif

    " Set the tab page number ('T' enables mouse support)
    let l:tabline_str .= '%' . (l:i + 1) . 'T'

    " Generate tab label: " ³[2] main.c "
    " Convert window count to superscript (`³` part)
    let l:win_count = tabpagewinnr(l:i + 1, '$')
    let l:win_count_sup = l:win_count < 10 ? s:superscripts[l:win_count] : '^' . l:win_count

    " Get active buffer name in curr tab (buflist is 0-indexed, winnr is 1-indexed)
    let l:buflist = tabpagebuflist(l:i + 1)
    let l:winnr = tabpagewinnr(l:i + 1)
    let l:bufnr = l:buflist[l:winnr - 1] 
    let l:bufname = bufname(l:bufnr)
    let l:buf_filetype = getbufvar(l:bufnr, '&filetype')

    " Set filename (`main.c` part)
    if l:buf_filetype == 'netrw'
      let l:filename = '(' . fnamemodify(getbufvar(l:bufnr, 'netrw_curdir'), ':~') . ')'
    elseif l:buf_filetype == 'qf'
      let l:filename = '(QF) %{QFTabline()}'
    else
      let l:filename = fnamemodify(l:bufname, ':t')
      if l:filename == ''
        let l:filename = '-No Name-'
      endif
    endif

    " Append a '*' if the buffer has unsaved changes
    if getbufvar(l:bufnr, '&modified')
      let l:filename .= '*'
    endif

    let l:tabline_str .= ' ' . l:win_count_sup . '[' . (l:i + 1) . '] ' . l:filename . ' '
  endfor

  " Add the label to close the current tab page
  if tabpagenr('$') > 1
    let l:tabline_str .= '%#TabLine#%999X|x|'
  endif

  " Fill the remaining blank space with TabLineFill highlighting
  let l:tabline_str .= '%#TabLineFill#%T'
  let l:tabline_str .= '%#TabLineInfo#%T'

  let l:tabline_str .= '%=[%{QFTabline()}] ' . s:makeprg_cmd_name
  let l:tabline_str .= " | %{strftime('%H:%M')}"

  return l:tabline_str
endfunction

set tabline=%!NazTabline()

"------------------------------
" Statusline
"
function! NazStatusline()
  let l:statusline_str = '[%n]' " buffer number

  let l:bufnr = winbufnr(g:statusline_winid)
  let l:buf_filetype = getbufvar(l:bufnr, '&filetype')

  if l:buf_filetype == 'netrw'
    let l:statusline_str .= ' %#Directory#' . fnamemodify(getbufvar(l:bufnr, 'netrw_curdir'), ':t') . '/%*'
    let l:len_mark_list = len(s:nazrw_mark_list)
    if l:len_mark_list > 0
      let l:statusline_str .= ' %#WarningMsg#[M:' . l:len_mark_list . ']%*'
    endif
  else
    let l:statusline_str .= ' %F %m%r'
  endif

  let l:statusline_str .= ' %=ch(%b) | %l:%c-%L ↓%p%%'
  return l:statusline_str
endfunction

set statusline=%!NazStatusline()


"============================================================
" Cursor & Background
"============================================================
if has("gui_running") || exists("g:neovide")
  "set guifont=Liberation\ Mono:h12
  set guifont=Cousine:h12

  set guicursor=n-v-c:block-Cursor,i-ci-ve-t:ver25-iCursor,r-cr:hor20-iCursor,o:hor50-oCursor
  highlight Cursor gui=NONE guifg=Red guibg=#00ff00
  highlight iCursor gui=NONE guifg=Black guibg=#ff0000
  highlight oCursor gui=NONE guifg=Black guibg=#00ffff
else
  let &t_SI = "\e[5 q" " Blinking bar for Insert mode
  let &t_SR = "\e[3 q" " Blinking underline for Replace mode
  let &t_EI = "\e[1 q" " Blinking block for Normal mode
endif

autocmd InsertEnter * set cursorline
autocmd InsertLeave * set nocursorline

let s:bg_colors = ['#101622', '#000d1a', '#171d2a', '#171a22']
let s:bg_index = 0

function! s:CycleBackground(prev)
  if a:prev
    let s:bg_index = (s:bg_index - 1 + len(s:bg_colors)) % len(s:bg_colors)
  else
    let s:bg_index = (s:bg_index + 1) % len(s:bg_colors)
  endif

  let l:next_color = s:bg_colors[s:bg_index]

  execute 'highlight Normal guibg=' . l:next_color
endfunction

command! CycleBGNext call s:CycleBackground(0)
command! CycleBGPrev call s:CycleBackground(1)

nnoremap <leader>bgn :CycleBGNext<CR>
nnoremap <leader>bgN :CycleBGPrev<CR>


"============================================================
"  Neovide
"============================================================
if exists("g:neovide")
  " Initial scale
  if !exists('g:neovide_scale_factor')
    let g:neovide_scale_factor = 1.0
  endif

  let g:neovide_scroll_animation_length = 0.2

  nnoremap <C-=> :let g:neovide_scale_factor += 0.1<CR>
  nnoremap <C--> :let g:neovide_scale_factor -= 0.1<CR>
  nnoremap <C-0> :let g:neovide_scale_factor = 1.0<CR>
  nnoremap <A-Enter> :let g:neovide_fullscreen = (g:neovide_fullscreen) ? v:false : v:true<CR>

  " Make arrow keys behave like Vim in wildmenu
  cnoremap <expr> <down>    wildmenumode() ? '<right>' : '<down>'
  cnoremap <expr> <up>      wildmenumode() ? '<left>'  : '<up>'
  cnoremap <expr> <right>   wildmenumode() ? '<down>'  : '<right>'
endif

"------------------------------
" Contents of init.lua
"
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" Linux path: `~/.config/nvim/init.lua`
" Windows path: `%localappdata%\nvim\init.lua`
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"-- Vim paths to Neovim
"local vimrc_path = ""
"local vimfiles_dir = ""
"
"if vim.fn.has('win32') == 1 or vim.fn.has('win64') == 1 then
"  vimrc_path = vim.fn.expand('~/vimfiles/vimrc')
"  vimfiles_dir = vim.fn.expand('~/vimfiles')
"else
"  vimrc_path = vim.fn.expand('~/.config/vim/vimrc')
"  vimfiles_dir = vim.fn.expand('~/.config/vim')
"end
"
"vim.opt.runtimepath:prepend(vimfiles_dir)
"vim.opt.runtimepath:append(vimfiles_dir .. '/after')
"vim.opt.packpath = vim.opt.runtimepath:get()
"
"-- Source my vimrc
"vim.cmd('source ' .. vimrc_path)
"
"-- Override $MYVIMRC (for <leader> 'erc' and 'src')
"vim.env.MYVIMRC = vimrc_path
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
