#!/bin/bash

# Usage:
#   v [--vim] [--edit | --term] [-e | -t | -d] [files...]
#
# Description:
#   Generate terminal-to-host / remote Vim or Nvim command calls
#
# Options:
#   --vim     Use Vim instead of Neovim (must be the first argument)
#   -e        Edit file in the current window (default)
#   -t        Edit file in a new tab
#   -d        Open two files in a new tab and `windo diffthis`
#   --edit    Open the `v` script for editing (at $HOME/.config/vim/v/v)
#   --term    Open current directory (netrw) and launch germinal on a new tab
#
# Examples:
#   v .                   Open current directory     ($ nvim --server $NVIM --remote .)
#   v --vim -t main.c     Open `main.c` in a new tab ($ vim --servername SERVER --remote-tab main.c)
#   v -d file_a file_b    Diff `file_a` (lhs) and `file_b` (rhs)
#     ($ nvim --server $NVIM --remote-tab file_a
#      $ nvim --server $NVIM --remote-send "<C-\><C-n> :execute 'vert split ' . fnameescape('file_b') | windo diffthis<CR>")
#
#  Note: if there's no Vim or Neovim server, launch new Vim/Neovide instance


V_PRG="nvim"
V_SERVER_OP="--server"
V_REMOTE_OP="--remote"
V_SERVER="$NVIM"
V_ARGS=()
V_DIFF=0
V_TERM=0
V_FILE_A=""
V_FILE_B=""


# ==================================================
# Argument parsing
# ==================================================

# Check for the `--vim` (only on $1) flag to set V_PRG to Vim or NeoVim
if [[ "$1" == "--vim" ]]; then
  V_PRG="vim"
  V_SERVER_OP="--servername"
  V_SERVER=$(vim --serverlist | head -n 1)
  shift
fi

# Set var based on the flag `-e = --remote`, `-t` = remote-tab)
if [ "$1" == "-e" ]; then
  shift
elif [ "$1" == "-t" ]; then
  V_REMOTE_OP="--remote-tab"
  shift
elif [ "$1" == "-d" ]; then
  V_DIFF=1
  V_FILE_A=$(realpath "$2")
  V_FILE_B=$(realpath "$3")
  shift 3
fi

if [ "$V_DIFF" -eq 0 ]; then
  # If there are no arguments left or `--term`, default to open Netrw on dir
  if [ -z "$1" ]; then
    V_ARGS=(".")
  elif [ "$1" == "--term" ]; then
    V_ARGS=(".")
    V_TERM=1
  elif [ "$1" == "--edit" ]; then
    V_ARGS=("$HOME/.config/vim/v/v")
  else
    # Loop through remaining args
    while [ $# -gt 0 ]; do
      curr_arg="$1"
      prefix="${curr_arg:0:1}"

      if [ "$prefix" != "-" ] && [ "$prefix" != "+" ]; then
        curr_arg=$(realpath "$curr_arg")
      fi

      V_ARGS+=("$curr_arg")
      shift
    done
  fi
fi


# ==================================================
# Running commands
# ==================================================

# If V_PRG is nvim and there's no Neovide instance, define a server socket and
# launch Neovide, passing --listen to nvim (sleep to wait for Neovide to open)
if [ -z "$V_SERVER" ]; then
  if [ "$V_PRG" == "nvim" ]; then
    export NVIM="/tmp/neovide_v_server"
    V_SERVER="/tmp/neovide_v_server"
    neovide -- --listen "$NVIM" &
  else
    V_SERVER="VIM_v_server"
    "$TERMINAL" --execute vim --servername "$V_SERVER" &
  fi
  sleep 1
fi

if [ "$V_DIFF" -eq 1 ]; then
  "$V_PRG" "$V_SERVER_OP" "$V_SERVER" --remote-tab "$V_FILE_A"
  "$V_PRG" "$V_SERVER_OP" "$V_SERVER" --remote-send "<C-\><C-n>:execute 'vert split ' . fnameescape('$V_FILE_B') | windo diffthis<CR>"
else
  # [@] expand the elements of the array with spaces between them
  "$V_PRG" "$V_SERVER_OP" "$V_SERVER" "$V_REMOTE_OP" "${V_ARGS[@]}"
  if [ "$V_TERM" -eq 1 ]; then
    sleep 1
    "$V_PRG" "$V_SERVER_OP" "$V_SERVER" --remote-send "<C-\><C-n> :Terminal<CR>"
  fi
fi
