#!/bin/bash

# v [--vim] <-e, -t, -d> [--edit] [Vim/Nvim arguments]
# Possible commands ...
# Neovide/NeoVim:
#   > v (`nvim --server $NVIM --remote .`)
#   > v -e <NVIM ARGS>   (`nvim --server $NVIM --remote <NVIM ARGS>`)
#   > v -t <NVIM ARGS>   (`nvim --server $NVIM --remote-tab <NVIM ARGS>`)
#   > v -d <file> <file> (`nvim --server $NVIM --remote-tab <NVIM ARGS>`)
# Vim:
#   > v --vim (`vim --server VIM --remote .`)
#   > v --vim -e <VIM ARGS> (`vim --server VIM --remote <VIM ARGS>`)
#   > v --vim -t <VIM ARGS> (`vim --server VIM --remote-tab <VIM ARGS>`)
#   > v --vim -d {file_a} {file_b} (
#     `vim --server VIM --remote-tab {file_a}`
#     `vim --server VIM --remote-send ":vert split | edit {file_b} | windo diffthis`
#   )

V_PRG="nvim"
V_SERVER_OP="--server"
V_REMOTE_OP="--remote"
V_SERVER="$NVIM"
V_ARGS=()
V_DIFF=0
V_TERM=0
V_FILE_A=""
V_FILE_B=""

# ==================================================
# Argument parsing
# ==================================================

# Check for the `--vim` (only on $1) flag to set V_PRG to Vim or NeoVim
if [[ "$1" == "--vim" ]]; then
  V_PRG="vim"
  V_SERVER_OP="--servername"
  V_SERVER=$(vim --serverlist | head -n 1)
  shift
fi

# Set var based on the flag `-e = --remote`, `-t` = remote-tab)
if [ "$1" == "-e" ]; then
  shift
elif [ "$1" == "-t" ]; then
  V_REMOTE_OP="--remote-tab"
  shift
elif [ "$1" == "-d" ]; then
  V_DIFF=1
  V_FILE_A=$(realpath "$2")
  V_FILE_B=$(realpath "$3")
  shift 3
fi

if [ "$V_DIFF" -eq 0 ]; then
  # If there are no arguments left or `--term`, default to open Netrw on dir
  if [ -z "$1" ]; then
    V_ARGS=(".")
  elif [ "$1" == "--term" ]; then
    V_ARGS=(".")
    V_TERM=1
  elif [ "$1" == "--edit" ]; then
    V_ARGS=("$HOME/.config/vim/v/v")
  else
    # Loop through remaining args
    while [ $# -gt 0 ]; do
      curr_arg="$1"
      prefix="${curr_arg:0:1}"

      if [ "$prefix" != "-" ] && [ "$prefix" != "+" ]; then
        curr_arg=$(realpath "$curr_arg")
      fi

      V_ARGS+=("$curr_arg")
      shift
    done
  fi
fi


# ==================================================
# Running commands
# ==================================================

# If V_PRG is nvim and there's no Neovide instance, define a server socket and
# launch Neovide, passing --listen to nvim (sleep to wait for Neovide to open)
if [ -z "$V_SERVER" ]; then
  if [ "$V_PRG" == "nvim" ]; then
    export NVIM="/tmp/neovide_v_server"
    V_SERVER="/tmp/neovide_v_server"
    neovide -- --listen "$NVIM" &
  else
    V_SERVER="VIM_v_server"
    "$TERMINAL" --execute vim --servername "$V_SERVER" &
  fi
  sleep 1
fi

if [ "$V_DIFF" -eq 1 ]; then
  "$V_PRG" "$V_SERVER_OP" "$V_SERVER" --remote-tab "$V_FILE_A"
  "$V_PRG" "$V_SERVER_OP" "$V_SERVER" --remote-send "<C-\><C-n>:execute 'vert split ' . fnameescape('$V_FILE_B') | windo diffthis<CR>"
else
  # [@] expand the elements of the array with spaces between them
  echo "$V_PRG"
  "$V_PRG" "$V_SERVER_OP" "$V_SERVER" "$V_REMOTE_OP" "${V_ARGS[@]}"
  if [ "$V_TERM" -eq 1 ]; then
    sleep 1
    "$V_PRG" "$V_SERVER_OP" "$V_SERVER" --remote-send "<C-\><C-n> :Terminal<CR>"
  fi
fi
