#!/usr/bin/env bash

# Map tablet output to target monitor
TARGET_MONITOR="eDP"
if xrandr --listmonitors | grep -q "HDMI-A-0"; then
  TARGET_MONITOR="HDMI-A-0"
fi

~/nazcripts/dtablet-map-to-output.sh $TARGET_MONITOR

notify-send "autorandr" "ran ~/.config/autorandr/postswitch"
