#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot -z $PICTURE"

BLUR="5x4"

$SCREENSHOT
magick $PICTURE -blur $BLUR $PICTURE
i3lock --image=$PICTURE --ignore-empty-password --show-failed-attempts --show-keyboard-layout
rm $PICTURE
